#!/bin/bash
export smog_exec=`which smog2`
if [ -z "$smog_exec" ]
then
	echo "

COULD NOT FIND USABLE VERSION OF SMOG 2!  QUITTING

"
	exit 1
fi

export perl4smog=`tail -n 1 $smog_exec| awk '{print $1}'`

export SMOG_PATH=`tail -n 1 $smog_exec| awk '{print $2}' | sed "s/src\/smogv2$//g"`

echo executable to be tested: $smog_exec
echo perl to be used: $perl4smog
echo smog path: $SMOG_PATH

dir=$(pwd)
count=0
if [ -z "$SMOG_PATH" ]; then
	echo ERROR: quick-check needs to know where SMOG2 is
	echo Use configure script in SMOG2 distribution to set up SMOG_PATH
	exit 1
fi
echo "Using the executables found in $SMOG_PATH"

for pdb in 1AKEapo_v2 1ypa.2chains 2GIS_noSAM_v2
do
for graining in AA CA AAgauss
do

if [ -e $dir/share/benchmarks/$pdb.$graining.pdb ]
then

if [ -d testing ]
then
rm -r testing
fi
mkdir testing

echo Testing $pdb with a $graining graining

if [ $graining == "AA" ]
then
	grainingText="AA"
elif [ $graining == "CA" ]
then
	grainingText="CA"
elif [ $graining == "AAgauss" ]
then
	grainingText="t $SMOG_PATH/share/templates/SBM_AA+gaussian"
fi

$perl4smog $smog_exec -i $dir/share/benchmarks/$pdb.$graining.pdb -$grainingText -dname testing/$pdb.$graining  &> testing/smog2.output
$perl4smog bin/quick_check.pl share/benchmarks/$pdb.$graining.top testing/$pdb.$graining.top &> testing/$pdb.$graining.test

a=$(grep ERROR testing/$pdb.$graining.test | wc -l | awk '{print $1}')
b=$(grep "Your Structure-based Model is ready" testing/smog2.output | wc -l | awk '{print $1}')

if [ $a -gt 0 ]
then
echo There are errors. Check testing/$pdb.$graining.test for details.
exit
elif [ $b -eq 0 ]
then
echo SMOG2 did not finish running. Check testing/smog.output for details.
exit
else
echo Congratulations there are no errors for $pdb.$graining.
fi
fi

done
done
exit
rm -r testing
echo "************ No errors found ************"

