#!/bin/bash

echo "Using the executables found in $SMOG_PATH"
echo "This is set when running configure.smog2"
export BIFSIF_AA_DEFAULT=$SMOG_PATH/SBM_AA
export BIFSIF_CA_DEFAULT=$SMOG_PATH/SBM_calpha
export BIFSIF_AA_TESTING=`pwd`/share/templates/SBM_AA
export BIFSIF_CA_TESTING=`pwd`/share/templates/SBM_calpha
export BIFSIF_STATIC_TESTING=`pwd`/share/templates/SBM_AA_STATIC
export TOLERANCE=0.001
export PRECISION=10000

bin/cleanup.bash
mkdir FAILED
echo share/PDB.files/all.pdbs | $perl4smog bin/check.shadow.all.v2.pl
