#!/bin/bash

rerun=$1

echo Detecting configured version of SMOG2
# grab all of the environment settings used when running smog2
export smog_exec=`which smog2`
export perl4smog=`tail -n 1 $smog_exec| awk '{print $1}'`
export SMOG_PATH=`tail -n 1 $smog_exec| awk '{print $2}' | sed "s/src\/smogv2$//g"`
`grep PERL $smog_exec`

echo "Using the files found in $SMOG_PATH"
echo "This is set when running configure.smog2"
export BIFSIF_AA_DEFAULT=$SMOG_PATH/SBM_AA
export BIFSIF_CA_DEFAULT=$SMOG_PATH/SBM_calpha
export BIFSIF_AA_TESTING=`pwd`/share/templates/SBM_AA
export BIFSIF_CA_TESTING=`pwd`/share/templates/SBM_calpha
export BIFSIF_STATIC_TESTING=`pwd`/share/templates/SBM_AA_STATIC
export TOLERANCE=0.001
export PRECISION=10000

bin/cleanup.bash
mkdir FAILED
echo share/PDB.files/all.pdbs | $perl4smog bin/check.v2.pl $rerun
