#!/bin/bash

SMOG_ROOT=$1
source $SMOG_ROOT/config.bash $SMOG_ROOT
export EXEC_SMOG=$SMOG_ROOT/smogv2

export BIFSIF=templates/SBM_AA
export BIFSIF_AA_STATIC=templates/SBM_AA_STATIC
export BIFSIF_CA=templates/SBM_calpha

export TOLERANCE=0.001
export PRECISION=10000

checkCA=1
checkAA=1


if [ $checkCA == 1 ]
then
	echo STARTING the shadow analysis with CA
	rm -r FAILED.shadow.CA
	mkdir FAILED.shadow.CA
	for i in ci2.CA 1AKEapo.CA rop.CA 3IZH
	do
		echo inputfiles/input.$i | bin/check.shadow.CA.v2.pl
	done
fi


if [ $checkAA == 1 ]
then
	echo STARTING the shadow analysis
	rm -r FAILED.shadow
	mkdir FAILED.shadow
	for i in ci2 SAM_v2 3IZH  rib DNA 
	do
		echo inputfiles/input.$i | bin/check.shadow.v2.pl
	done
fi
